---
title: "Project1_RM"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(geosphere)

options(scipen=999)
```

```{r}
knitr::opts_chunk$set(echo = TRUE)
airbnb <-read.csv(file="/Users/reagan/Documents/_SMU/Spring_2020/Applied_Statistics/Applied_Stats_Project/Project_1/AB_NYC_2019.csv",header=TRUE)

airbnb <- filter(airbnb, substr(last_review, 1, 4) %in% c('2017', '2018', '2019'))

airbnb <- filter(airbnb, price >= 25 & price <= 400)

airbnb$id <- NULL
airbnb$name <- NULL
airbnb$host_id <- NULL
airbnb$host_name <- NULL
airbnb$host_listings <- airbnb$calculated_host_listings
airbnb$calculated_host_listings <- NULL

#Creating a new, tsquare_distance (distance to Times Square in miles)
for (i in 1:nrow(airbnb)) {
  n <- (distHaversine(c(airbnb$latitude[i], -airbnb$longitude[i]), c(40.7580, 73.9855)) / 1609.344)
  airbnb$tsquare_distance[i] <- n
}

selected_vars <- c('neighbourhood_group', 'neighbourhood', 'room_type', 'price', 'minimum_nights', 'number_of_reviews', 'reviews_per_month', 'host_listings', 'tsquare_distance', 'availability_365')
airbnb <- airbnb[selected_vars]

airbnb <- airbnb[!(airbnb$price==0),]
airbnb <- airbnb[!(airbnb$availability_365==0),]

airbnb_EH <- filter(airbnb, room_type == "Entire home/apt")
airbnb_PR <- filter(airbnb, room_type == "Private room")
airbnb_SR <- filter(airbnb, room_type == "Shared room")
```

```{r}
fit <- lm(log(price) ~ minimum_nights + number_of_reviews + tsquare_distance + neighbourhood + room_type + neighbourhood:room_type, data = airbnb)
summary(fit)
plot(fit)
``` 

